name       : gbml
version    : 1.4.0.0
release    : 3
source     :
    - https://gitlab.com/supremesonicbrazil/GBML/-/archive/v1.4.0.0/GBML-v1.4.0.0.tar.gz : 93a49aa609020fc2ba056962fe2d98d65c65687ac9856d1aceaf3fe297908780
license    : GPL-3.0-or-later
component  : games.platformer
summary    : Gaming Backup Multitool for Linux
description: |
    Gaming Backup Multitool for Linux - Backup utility and database for Linux Steam games 
rundeps    :
    - steam
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Widgets)
    - sqlite3
build      : |
    ./BUILD.sh
install    : |
    install -Dm755 ./bin/gbml "$installdir"/usr/bin/gbml
    install -Dm644 ./bin/SteamLinuxGames.db "$installdir"/usr/share/gbml/SteamLinuxGames.db
    install -Dm644 ./bin/gaming-backup-multitool-linux.desktop "$installdir"/usr/share/applications/gaming-backup-multitool-linux.desktop
    cp -r ./img "$installdir"/usr/share/gbml
